; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "Ãנאלמעוי"
#define MyAppVersion "0.0.0.44"
#define MyAppPublisher "Äודעÿנוג À.À."
#define MyCopyright "© Äודעÿנוג À.À., 2020"
#define MyAppURL "https://github.com/wofs/gramotei"
#define MyAppExeName "gramotei.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{B1798FE0-E0E9-44A1-89BC-4D8D9298BB3E}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
VersionInfoProductName={#MyAppName}
VersionInfoVersion={#MyAppVersion}
VersionInfoCompany={#MyAppPublisher}
VersionInfoCopyright={#MyCopyright}
DefaultDirName={autopf}\{#MyAppName}
LicenseFile=C:\Z\Projects\lazarus\gramotei\bin\LICENSE.txt
InfoBeforeFile=C:\Z\Projects\lazarus\gramotei\ChangeLog.txt
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
OutputDir=C:\Z\Projects\lazarus\gramotei\setup
OutputBaseFilename=GramoteiSetup
SetupIconFile=C:\Z\Projects\lazarus\gramotei\gramotei.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern
CloseApplications = true

[Languages]
Name: "russian"; MessagesFile: "compiler:Languages\Russian.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Z\Projects\lazarus\gramotei\bin\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

